apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.app.name }}
  {{- template "common.metadata" . }}
webhooks:
  - name: {{ .Values.app.name }}.aks-webhook-ns.svc
    clientConfig:
      service:
        name: {{ .Values.app.name }}
        namespace: {{ .Values.namespace }}
        path: "/"
        port: 1337
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"] 
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        mutating-webhook: enabled